apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: publisher
  template:
    metadata:
      labels:
        name: publisher
    spec:
